name=MR-1
version=1.0.0
author=Matheus Lino
maintainer=Matheus Lino (contato@moddena.com.br)
sentence=MR-1 Robot Arm library.
paragraph=Drives motors, generates trajectories, and handles communication with the teaching pendant.
category=Device Control
url=https://www.moddena.com.br/
architectures=*
precompiled=full
